[profile.default]
solc = "0.8.19"
# optimizer = false
# optimizer_runs = 0
optimizer = true
optimizer_runs = 1_000
# optimizer_runs = 1000_000
# bytecode_hash = "none"

fs_permissions = [{ access = "read-write", path = "./" }]
rpc_endpoints = { mainnet = "https://rpc.ankr.com/eth", optimism = "https://rpc.ankr.com/optimism", fantom = "https://rpc.ankr.com/fantom", arbitrum = "https://rpc.ankr.com/arbitrum", bsc = "https://rpc.ankr.com/bsc", moonriver = "https://moonriver.public.blastapi.io", gnosis = "https://rpc.ankr.com/gnosis", avax = "https://rpc.ankr.com/avalanche", polygon = "https://rpc.ankr.com/polygon" }


[fuzz]
# runs = 1_000
runs = 10_000
# runs = 1_000_000


[fmt]
bracket_spacing = true
int_types = "long"
multiline_func_header = "all"
number_underscore = "preserve"
quote_style = "double"
tab_width = 4
# wrap_comments = true
